environment:
  matrix:
    - nodejs_version: "Stable"
    - nodejs_version: "LTS"

cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: $env:VERSION = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:VERSION-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn ci

build: off
